created_at: '2025-11-25T12:18:04.267638'
features:
  efficiency_features:
  - season_targets_per_game
  - season_yards_per_game
  - yards_per_reception
  - yards_per_target
  rolling_features:
  - roll_3g_yds
  - roll_3g_tgt
  - roll_3g_rec
  - roll_3g_yac
  - roll_3g_first_dwn
  - roll_3g_aybc
  - roll_3g_td
  - roll_5g_yds
  - roll_5g_tgt
  - roll_5g_rec
  - roll_5g_yac
  - roll_5g_first_dwn
  - roll_5g_aybc
  - roll_5g_td
  total_features: 18
filter: has_min_games_3g
hyperparameters:
  max_depth: 15
  min_samples_leaf: 2
  min_samples_split: 5
  n_estimators: 200
  n_jobs: -1
  random_state: 42
model_type: RandomForestRegressor
target: next_week_rec_yds
test_years:
- 2024
train_years:
- 2022
- 2023
version: v1_baseline
